---
title: "Hungarian COVID-19 deaths vs. Google's mobility data"
author: "Bence E. Bakos"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Packages

```{r packages}
library(tidyverse)
```

# Data

Documentation for data:

- [Google Mobility Data](https://www.google.com/covid19/mobility/data_documentation.html)
- [Our World in Data COVID-19 dataset](https://github.com/owid/covid-19-data/tree/master/public/data)

```{r data}
# Downloading mobility data from Google
download.file(url = "https://www.gstatic.com/covid19/mobility/Region_Mobility_Report_CSVs.zip",
              destfile = "Data/Region_Mobility_Report_CSVs.zip")

# Unzipping relevant files
unzip(zipfile = "Data/Region_Mobility_Report_CSVs.zip",
      files = "2020_HU_Region_Mobility_Report.csv",
      exdir = "Data")

unzip(zipfile = "Data/Region_Mobility_Report_CSVs.zip",
      files = "2021_HU_Region_Mobility_Report.csv",
      exdir = "Data")

# Importing relevant files
mobility_hu_20 <- read_csv("Data/2020_HU_Region_Mobility_Report.csv")
mobility_hu_21 <- read_csv("Data/2021_HU_Region_Mobility_Report.csv")

# Downloading and importing COVID-19 data from Our World in Data
owd_covid_HU <-
  read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") %>% 
  filter(iso_code == "HUN")
```

# Data Wrangling

Google's mobility data is divided into separate files by year. Below I join the dataframes and create a separate DF for Hungary overall, and a DF with all subregions. Mobility data and COVID-19 data also need to be joined.

```{r wrangling}
# Joining dataframes
mobility_hu <- bind_rows(mobility_hu_20, mobility_hu_21)

# New dataframe for Hungary overall
mobility_hu_OVR <-
  mobility_hu %>% 
  filter(is.na(sub_region_1) == TRUE) %>% 
  select(date:last_col())

# New dataframe for subregions of Hungary
mobility_hu_sub <-
  mobility_hu %>% 
  filter(is.na(sub_region_1) == FALSE) %>% 
  select(c(sub_region_1, iso_3166_2_code, date:last_col()))

# Selecting relevant variables
owd_covid_HU <-
  owd_covid_HU %>% 
  select(c(date, new_cases:new_deaths_smoothed_per_million,
           people_vaccinated:new_vaccinations_smoothed,
           people_fully_vaccinated_per_hundred:new_vaccinations_smoothed_per_million))

# Joining mobility and COVID-19 data
mobility_covid <- 
  mobility_hu_OVR %>% 
  left_join(owd_covid_HU, by = "date")

# Joining mobility and COVID-19 data for subregions
mobility_covid_subregions <-
  mobility_hu_sub %>% 
  left_join(owd_covid_HU, by = "date")
```
